name: Capstone Project Services- GCP Deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VM_NAME: vm-services-seed
      INSTANCE_GROUP: mig-services
      INSTANCE_TEMPLATE: temp-vm-services-seed-v1
      REGION: asia-southeast1
      ZONE: asia-southeast1-c
      USER_NAME: zeejmaleeshamadushanka
      IMAGE_NAME: vm-services-seed-boot-image

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v3.0.1

      - name: Get Dynamic VM Name and Start Instance
        run: |
          ACTUAL_NAME=$(gcloud compute instance-groups managed list-instances ${{ env.INSTANCE_GROUP }} \
            --region=${{ env.REGION }} \
            --format="value(instance.scope().basename())" \
            --limit=1)
          
          echo "Detected VM Name: $ACTUAL_NAME"
          echo "VM_NAME=$ACTUAL_NAME" >> $GITHUB_ENV
          gcloud compute instances start $ACTUAL_NAME --zone=${{ env.ZONE }}

      - name: Connect with the VM through SSH, force-sync code, and build
        run: >
          gcloud compute ssh ${{ env.USER_NAME }}@${{ env.VM_NAME }} --zone=${{ env.ZONE }}
          --command "echo 'Connected successfully!' &&
          cd Capstone-Project-Services/ &&
          git fetch --all &&
          git reset --hard origin/main &&
          git submodule foreach --recursive 'git clean -fd && git reset --hard' &&
          git submodule update --init --recursive --force &&
          source ~/.bashrc &&
          mvn clean package
          "

      - name: Stop the VM instance
        run: gcloud compute instances stop ${{ env.VM_NAME }} --zone=${{ env.ZONE }}

      - name: Delete the old boot disk image
        run: gcloud compute images delete ${{ env.IMAGE_NAME }} --quiet
        continue-on-error: true

      - name: Create a new boot disk image
        run: |
          gcloud compute images create ${{ env.IMAGE_NAME }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --source-disk=${{ env.VM_NAME }} \
            --source-disk-zone=${{ env.ZONE }} \
            --storage-location=${{ env.REGION }}

      - name: Update the instance group with the new image
        run: |
          gcloud compute instance-groups managed rolling-action start-update ${{ env.INSTANCE_GROUP }} \
            --region=${{ env.REGION }} \
            --type=proactive \
            --max-unavailable=0 \
            --minimal-action=replace \
            --replacement-method=substitute \
            --max-surge=3 \
            --version=template=projects/${{ secrets.GCP_PROJECT_ID }}/regions/${{ env.REGION }}/instanceTemplates/${{ env.INSTANCE_TEMPLATE }}